### ISSUE TITLE
setup.py missing

### ISSUE THREAD

**Issue by Kexanone** [vandan-revanur/pychemovality#1]
Would be nice if you add a `setup.py`, such that it can be installed as a Python module.

**Comment by vandan-revanur** [comment]
@Kexanone setup.py installs with pip are deprecated. 

Hence I have added a pyproject.toml which you can use to install the `pychemovality` library like this: 

`pip install pyproject.toml`

**Comment by Kexanone** [comment]
Ah, thanks for the hint! I indeed wasn't aware of PEP 517. Time to update my Python modules xD
